global:
  resolve_timeout: 30s

route:
  receiver: incident-api
  group_by: [alertname, service]
  group_wait: 1s
  group_interval: 2s
  repeat_interval: 1m

receivers:
  - name: incident-api
    webhook_configs:
      - url: http://incident-api:8000/api/v1/alerts
        send_resolved: true
        max_alerts: 10
